version: '3'


services:
  pulsar:
    image: apachepulsar/pulsar:2.9.2
    container_name: yami-pulsar
    restart: unless-stopped
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    # networks:
    #   - yami

volumes:
  pulsardata: {}
  pulsarconf: {}

# networks:
#   yami:
#     name: yami
#     external: true