version: '3'


services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: yami-rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - yami


networks:
  yami:
    name: yami
    external: true