version: '3'


services:
  pulsar:
    image: apachepulsar/pulsar:2.9.2
    container_name: yami-pulsar
    restart: unless-stopped
    command: bin/pulsar standalone
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    # networks:
    #   - yami

  seq:
    image: datalust/seq:latest
    container_name: yami-seq
    restart: unless-stopped
    ports:
      - 80:80
      - 5341:5341
    volumes:
      - seqdata:/data
    environment:
      - ACCEPT_EULA=y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FMzA7AvCLkH8NfOTFITAf3enkAxyiQqIgp7nznRWJfNSSqmzzg==
    

volumes:
  pulsardata: {}
  pulsarconf: {}
  seqdata: {}

# networks:
#   yami:
#     name: yami
#     external: true

# seq admin : password